<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDFa1KRW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDFa1KRW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDFa1KRW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDFa1KRW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDFa1KRW\App_KernelDevDebugContainer([
    'container.build_hash' => 'DFa1KRW',
    'container.build_id' => 'a598c42a',
    'container.build_time' => 1668006047,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDFa1KRW');
